const players = [
  {
    id: 1,
    name: 'Lionel Messi',
    goal: 36,
    assist: 122,
    img: './img/lionel-messi.webp',
  },
  {
    id: 2,
    name: 'Sergio Ramos',
    goal: 23,
    assist: 100,
    img: './img/sergio ramos.webp',
  },
  {
    id: 3,
    name: 'Vítor Machado',
    goal: 15,
    assist: 92,
    img: './img/vitor machado.webp',
  },
  {
    id: 4,
    name: 'Kylian Mbappé',
    goal: 21,
    assist: 112,
    img: './img/kylian mbapp.webp',
  },
  {
    id: 5,
    name: 'Neymar Jr',
    goal: 24,
    assist: 96,
    img: './img/neymar jr.webp',
  },
  {
    id: 6,
    name: 'Renato Sanches',
    goal: 17,
    assist: 100,
    img: './img/renato sanches.webp',
  },
  {
    id: 7,
    name: 'Ashley Cole',
    goal: 15,
    assist: 90,
    img: './img/ashley cole.webp',
  },
  {
    id: 8,
    name: 'Gianluigi Buffon',
    goal: 14,
    assist: 80,
    img: './img/gianluigi buffon.webp',
  },
  {
    id: 9,
    name: 'Cristiano Ronaldo',
    goal: 31,
    assist: 125,
    img: './img/cristiano ronaldo.webp',
  },
  {
    id: 10,
    name: 'Yaya Toure',
    goal: 19,
    assist: 102,
    img: './img/yaya toure.webp',
  },
]
